### ISSUE TITLE
restore updates

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/hound#17]
Following updates were lost in #16 

- [x] ui: collapse and expand files https://github.com/it-projects-llc/hound/commit/1d32469f947371fb00d242387f3b4a4d4a88ed2b#diff-c533b05da773f2ea1c7bec46470408c6

- [x] js: add the excludeFiles search parameter https://github.com/it-projects-llc/hound/commit/499342d86f8f44ee57c21cdc7d99f525f995d908#diff-c533b05da773f2ea1c7bec46470408c6

**Comment by Trivikramreddy** [comment]
These features seem to be very handy. When can we see these added again?

**Comment by yelizariev** [comment]
I postponed the project for a while. I can merge the fixes though if someone makes a pull request

**Comment by yelizariev** [comment]
@Trivikramreddy excludeFiles search is restored

**Comment by Trivikramreddy** [comment]
Thanks for the update @yelizariev

**Comment by Trivikramreddy** [comment]
@yelizariev  Are you planning to restore collapse and expand files in near future?

**Comment by yelizariev** [comment]
Yes, in a couple weeks I hope
