### ISSUE TITLE
New Release soon?

### ISSUE THREAD

**Issue by sluongng** [it-projects-llc/hound#26]
Hey guys, thanks for forking hound search.

I was wondering if you guys could provide a newer release soon? The last one was dated 2015.

I have some automation that will pick up and package stuff base on github release so not having to rely on master branch constantly would be quite nice.

Cheers.

**Comment by yelizariev** [comment]
It sounds like a good idea to use github releases. Thanks for the suggestion.
I expect to make updates in #17 soon and will make a release then.

**Comment by dufferzafar** [comment]
Hey, can you also provide built binaries?

**Comment by yelizariev** [comment]
I don't think that GitHub Packages supports what you are asking
