### ISSUE TITLE
make default ref configurable for git?

### ISSUE THREAD

**Issue by grimm26** [it-projects-llc/hound#54]
https://github.com/itpp-labs/hound/blob/master/vcs/git.go#L14 sets defaultRef iwth a `const` but it should be configurable per repo.  We are moving all of our repos from `master` to `main` as the default branch, for example.

**Comment by yelizariev** [comment]
You can configure it in vcs-config section. See https://github.com/itpp-labs/hound/blob/562589534f8b82858acdbf5fadfba9f5a02db424/config-example.json#L23
